id: PA43E468A
initial_creation_type: ocr
source_metadata:
  volumes:
    c6929b08260a4e9fa6a473e649df6d6b:
      base_file: v036.txt
      image_group_id: I1PD95881
      title: རྡོ་རྗེ་རྣམ་པར་འཇོམས་པ་ཞེས་བྱ་བའི་གཟུངས་ཀྱི་བཤད་པ།
      total_pages: 1869
      volume_number: 36
